import { AllowedOperation } from '../../settings/redux/allowedOperations/interfaces';
import { WorkCapacity } from '../../settings/redux/workcenterCapacities/interfaces';
import { WorkCenterResponse } from './../../settings/redux/workCenters/interfaces';

export const mockedWorkCentersData: WorkCenterResponse[] = [
  {
    department: {
      code: 'new_code',
      isActive: true,
      id: 10,
      name: 'new_name',
    },
    unitOfMeasure: {
      code: 'codetest1234511',
      isActive: false,
      id: 15,
      name: 'codetrst',
    },
    allocations: [{ id: 1, name: 'Recipe' }],
    departmentId: 10,
    allocationBased: 0,
    isActive: true,
    remark: 'Remark',
    unitOfMeasureId: 15,
    workCenterAddAndUpdateDto: [],
    id: 4,
    name: 'asdf',
    workCenter_Id: 1,
    workCenterInterfaceId: 'interface 1',
    departments: [
      {
        id: 2,
        name: 'dsa',
        code: '321c',
        isActive: true,
      },
    ],
    allocation: {
      id: 1,
      name: 'asds',
    },
    unitOfMeasures: [
      {
        id: 3,
        name: 'asd',
        code: 'codes',
        isActive: true,
      },
    ],
    allowedOperations: [],
    workCapacities: [
      {
        id: 1,
        workCenterId: 4,
        weekDay: '2022-12-13T14:56:52.065Z',
        dayOfWeek: 1,
        start: '2022-12-13T14:56:52.065Z',
        break: 0,
        end: '2022-12-13T14:56:52.065Z',
        minutes: 50,
        efficiency: 100,
        availableMinutes: 30,
        isWorkingDay: true,
        capacity: 120,
        changeHistoryDto: { createdBy: 'admin', createdOn: '2022-12-13T14:56:52.065Z' },
      },
    ],
    operations: [
      {
        department: {
          code: 'new_code',
          isActive: true,
          id: 10,
          name: 'new_name',
        },
        unitOfMeasure: {
          code: 'codetest1234511',
          isActive: false,
          id: 15,
          name: 'codetrst',
        },
        allocationBasedDtos: [],
        departments: [],
        unitOfMeasures: [],
        operation_Id: 1,
        departmentId: 10,
        allocationBased: 0,
        isActive: true,
        remark: 'Just small remark',
        unitOfMeasureId: 15,
        operationTime: 100,
        setupTime: 200,
        waitingTime: 300,
        interfaceCode: 'interfaceCode',
        id: 2,
        name: 'new_operation',
      },
    ],
  },
  {
    department: {
      code: 'new_code',
      isActive: true,
      id: 10,
      name: 'new_name',
    },
    unitOfMeasure: {
      code: 'codetest1234511',
      isActive: false,
      id: 15,
      name: 'codetrst',
    },
    departmentId: 10,
    allocationBased: 0,
    isActive: true,
    remark: 'Just small remark',
    workCenterAddAndUpdateDto: [],
    unitOfMeasureId: 14,
    id: 3,
    name: 'new_operation',
    workCenter_Id: 2,
    workCenterInterfaceId: 'interface 2',
    departments: [
      {
        id: 3,
        name: 'jyr',
        code: '543c',
        isActive: true,
      },
    ],
    allocation: {
      id: 22,
      name: 'sdf',
    },
    allocations: [{ id: 1, name: 'Recipe' }],
    unitOfMeasures: [
      {
        id: 1,
        name: 'fca',
        code: '23es',
        isActive: true,
      },
    ],
    allowedOperations: [],
    workCapacities: [
      {
        id: 2,
        workCenterId: 3,
        weekDay: '2022-12-13T14:56:52.065Z',
        dayOfWeek: 2,
        start: '2022-12-13T14:56:52.065Z',
        break: 70,
        end: '2022-12-13T14:56:52.065Z',
        minutes: 40,
        efficiency: 100,
        availableMinutes: 50,
        isWorkingDay: true,
        capacity: 230,
        changeHistoryDto: { createdBy: 'admin', createdOn: '2022-12-13T14:56:52.065Z' },
      },
    ],
    operations: [
      {
        department: {
          code: 'new_code',
          isActive: true,
          id: 10,
          name: 'new_name',
        },
        unitOfMeasure: {
          code: 'codetest1234511',
          isActive: false,
          id: 15,
          name: 'codetrst',
        },
        allocationBasedDtos: [],
        departments: [],
        unitOfMeasures: [],
        operation_Id: 11,
        departmentId: 10,
        allocationBased: 0,
        isActive: true,
        remark: 'Remark',
        unitOfMeasureId: 15,
        operationTime: 0.125,
        setupTime: 0.125,
        waitingTime: 0.125,
        interfaceCode: 'INTERFACE_CODE',
        id: 4,
        name: 'asdf',
      },
    ],
  },
];

export const mockedWorkCapacities: WorkCapacity[] = [
  {
    id: 1,
    workCenterId: 4,
    weekDay: '2022-12-13T14:56:52.065Z',
    dayOfWeek: 0,
    start: '2022-12-13T14:56:52.065Z',
    break: 0,
    end: '2022-12-13T14:56:52.065Z',
    minutes: 50,
    efficiency: 100,
    availableMinutes: 30,
    isWorkingDay: true,
    capacity: 120,
    changeHistoryDto: { createdBy: 'admin', createdOn: '2022-12-13T14:56:52.065Z' },
  },
];

export const mockedAllowedOperations: AllowedOperation[] = [
  {
    changeHistoryDto: { createdBy: 'admin', createdOn: '2022-12-13T14:56:52.065Z' },
    operation: {
      department: {
        code: 'new_code',
        isActive: true,
        id: 10,
        name: 'new_name',
      },
      unitOfMeasure: {
        code: 'codetest1234511',
        isActive: false,
        id: 15,
        name: 'codetrst',
      },
      allocationBasedDtos: [],
      departments: [],
      unitOfMeasures: [],
      operation_Id: 1,
      departmentId: 10,
      allocationBased: 0,
      isActive: true,
      remark: 'Just small remark',
      unitOfMeasureId: 15,
      operationTime: 100,
      setupTime: 200,
      waitingTime: 300,
      interfaceCode: 'interfaceCode',
      id: 2,
      name: 'new_operation',
    },
    id: 1,
    operationId: 1,
    workCenter: null,
    workCenterId: 1,
  },
];
